# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_effort <- function(n_after_move, m, waa, selq, effort_mult_initial, target, target_type, fishery_area) {
    .Call(`_tandoori_find_effort`, n_after_move, m, waa, selq, effort_mult_initial, target, target_type, fishery_area)
}

int_test <- function(dummy) {
    .Call(`_tandoori_int_test`, dummy)
}

simple_array_2D_as_wrap_test <- function(sa2d) {
    .Call(`_tandoori_simple_array_2D_as_wrap_test`, sa2d)
}

simple_array_2D_get_accessor_test <- function(sa2d, x, y) {
    .Call(`_tandoori_simple_array_2D_get_accessor_test`, sa2d, x, y)
}

get_catch_demo <- function(f, m, n, fishery_area) {
    .Call(`_tandoori_get_catch_demo`, f, m, n, fishery_area)
}

test_catch_weight <- function(effort_in, n_after_move, m, waa, selq, fishery_area) {
    .Call(`_tandoori_test_catch_weight`, effort_in, n_after_move, m, waa, selq, fishery_area)
}

simple_array_3D_as_wrap_test <- function(sa3d) {
    .Call(`_tandoori_simple_array_3D_as_wrap_test`, sa3d)
}

simple_array_3D_get_accessor_test <- function(sa3d, x, y, z) {
    .Call(`_tandoori_simple_array_3D_get_accessor_test`, sa3d, x, y, z)
}

