# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name get_error
#' @title Defines f(x) for effort minimisation.
#'
#' @description For catch fisheries:
#' \deqn{g(x) = \sum [log(C_{target}) - log(C(x))]^2}
#' For effort fisheries:
#' \deqn{h(x) = \sum [log(E_{target}) - log(x)]^2}
#' Error function is then \eqn{f(x) = \sqrt{g(x) + h(x)}}.
#'
#' @param nfisheries_ an integer number of fisheries
#' @param n_after_move a 2D array of numbers-at-age by area
#' @param m natural a 2D array of natural mortality-at-age by area
#' @param waa a 2D array of weight-at-age by fishery
#' @param selq a 2D array of selectivity-at-age by fishery
#' @param target numeric vector of targets by fishery
#' @param target_type integer vector of target types by fishery (0 = catch, 1 = effort)
#' @param fishery_map integer vector indicating which area each fishery operates in
#' @return f(x) evaluated at x.
NULL

#' Finds the effort that achieves the supplied catch target.
#'
#' Originally, solve_effort() was not exposed to R, but now it is exported to help with documentation.
#' Uses the LBFGSBSolver to perform minimisation. The minimised function, f(x), is of type EffortFun. See ?get_error.
#'
#' @param n_pre_move a 2D array of numbers-at-age by area
#' @param n0_pre_move a 2D array of unfished numbers-at-age by area
#' @param m a 2D array of natural mortality-at-age by area
#' @param waa a 2D array of weight-at-age by fishery
#' @param movement a 3D array of movement-at-age
#' @param selq a 2D array of selectivity-at-age by fishery
#' @param target numeric vector of targets by fishery
#' @param target_type integer vector of target types by fishery (0 = catch, 1 = effort)
#' @param fishery_area integer vector indicating which area each fishery operates in
#' @param max_effort numeric vector of maxmimum effort by fishery
#' @param max_solver_iters integer maximum number of solver iterations
#' @return list of effort, solver info and updated population quantities
solve_effort <- function(n_pre_move, m, waa, movement, selq, target, target_type, fishery_map, max_effort, max_solver_iters) {
    .Call(`_tandoori_solve_effort`, n_pre_move, m, waa, movement, selq, target, target_type, fishery_map, max_effort, max_solver_iters)
}

#' Finds the effort that achieves the supplied catch target.
#'
#' find_effort() is a wrapper for solve_effort() that is exposed to R.
#'
#' @param n_pre_move a 2D array of numbers-at-age by area
#' @param n0_pre_move a 2D array of unfished numbers-at-age by area
#' @param m natural a 2D array of natural mortality-at-age by area
#' @param waa a 2D array of weight-at-age by fishery
#' @param movement a 3D array of movement-at-age
#' @param selq a 2D array of selectivity-at-age by fishery
#' @param target numeric vector of targets by fishery
#' @param target_type integer vector of target types by fishery (0 = catch, 1 = effort)
#' @param fishery_area integer vector indicating which area each fishery operates in
#' @param max_effort numeric vector of maxmimum effort by fishery
#' @param max_solver_iters integer maximum number of solver iterations
#' @return list of solve_effort().
find_effort <- function(n_pre_move, m, waa, movement, selq, target, target_type, fishery_area, max_effort, max_solver_iters) {
    .Call(`_tandoori_find_effort`, n_pre_move, m, waa, movement, selq, target, target_type, fishery_area, max_effort, max_solver_iters)
}

#' Projects fishery with catch or effort targets.
#'
#' project() is mostly a wrapper for solve_effort() but also applies movement to the numbers-at-age arrays and calculates survivors and catch. Fisheries with catch targets require optimisation of effort to acheive target catch. solve_effort() is an internal function that can be accessed through the exposed function find_effort().
#'
#' @param n_pre_move a 2D array of numbers-at-age by area
#' @param n0_pre_move a 2D array of unfished numbers-at-age by area
#' @param m natural a 2D array of natural mortality-at-age by area
#' @param waa a 2D array of weight-at-age by fishery
#' @param movement a 3D array of movement-at-age
#' @param selq a 2D array of selectivity-at-age by fishery
#' @param target vector of targets by fishery
#' @param target_type vector of target types by fishery (0 = catch, 1 = effort)
#' @param fishery_area integer vector indicating which area each fishery operates in
#' @param max_effort numeric vector of maxmimum effort by fishery
#' @param max_solver_iters integer maximum number of solver iterations
#' @return list of effort, solver info and updated population quantities
project <- function(n_pre_move, n0_pre_move, m, waa, movement, selq, target, target_type, fishery_area, max_effort, max_solver_iters) {
    .Call(`_tandoori_project`, n_pre_move, n0_pre_move, m, waa, movement, selq, target, target_type, fishery_area, max_effort, max_solver_iters)
}

int_test <- function(dummy) {
    .Call(`_tandoori_int_test`, dummy)
}

simple_array_2D_constructor <- function(x, y, fill) {
    .Call(`_tandoori_simple_array_2D_constructor`, x, y, fill)
}

simple_array_2D_as_wrap_test <- function(sa2d) {
    .Call(`_tandoori_simple_array_2D_as_wrap_test`, sa2d)
}

simple_array_2D_get_accessor_test <- function(sa2d, x, y) {
    .Call(`_tandoori_simple_array_2D_get_accessor_test`, sa2d, x, y)
}

get_catch_demo <- function(f, m, n, fishery_area) {
    .Call(`_tandoori_get_catch_demo`, f, m, n, fishery_area)
}

test_2D_iterator <- function(sa2d) {
    .Call(`_tandoori_test_2D_iterator`, sa2d)
}

test_catch_weight <- function(effort_in, n_after_move, m, waa, selq, fishery_area) {
    .Call(`_tandoori_test_catch_weight`, effort_in, n_after_move, m, waa, selq, fishery_area)
}

simple_array_3D_as_wrap_test <- function(sa3d) {
    .Call(`_tandoori_simple_array_3D_as_wrap_test`, sa3d)
}

simple_array_3D_get_accessor_test <- function(sa3d, x, y, z) {
    .Call(`_tandoori_simple_array_3D_get_accessor_test`, sa3d, x, y, z)
}

simple_array_3D_constructor <- function(x, y, z, fill) {
    .Call(`_tandoori_simple_array_3D_constructor`, x, y, z, fill)
}

test_3D_iterator <- function(sa3d) {
    .Call(`_tandoori_test_3D_iterator`, sa3d)
}

movement_test <- function(n_pre_move, movement) {
    .Call(`_tandoori_movement_test`, n_pre_move, movement)
}

